name: release
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - beta
jobs:
  code:
    uses: mocktomata/.github/.github/workflows/pnpm-verify-linux.yml@main
  release:
    uses: mocktomata/.github/.github/workflows/pnpm-release-changeset.yml@main
    needs: code
    secrets: inherit
  docs:
    uses: mocktomata/.github/.github/workflows/pnpm-docs.yml@main
    needs: release
    secrets: inherit
