name: release
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - beta
jobs:
  docs:
    uses: mocktomata/.github/.github/workflows/pnpm-docs.yml@main
    secrets: inherit
    with:
      publish_dir: ./build
